### ISSUE TITLE
[BUG] Site Search delete X not keyboard navigable 

### ISSUE THREAD

**Issue by 72gm** [scottish-government-design-system/design-system#128]
## Description of the issue

You cannot keyboard tab onto the X to clear the search phrase 

![image](https://github.com/user-attachments/assets/2882d285-cada-4512-8357-76cbf373af5e)

## Steps to reproduce the issue

go to https://designsystem.gov.scot/components/site-search type in a search amount and try to tab onto the X to clear the search phrase

## Expected behaviour

From an accessibility point of view I'd expect to be able to use the keyboard to clear the search

- Operating system:
Chrome, Windows 11

**Comment by jsutcliffe** [comment]
This is a browser feature and not an explicit part of the Design System. Most modern browsers, with Firefox being the most notable exception, add a clear "x" to input elements of type "search". The search term can be cleared using a keyboard by pressing the "escape" key.

See [MDN's documentation on the search input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search#differences_between_search_and_text_types) for reference.
