### ISSUE TITLE
[BUG] Mismatch between breakpoints and table boxes

### ISSUE THREAD

**Issue by 72gm** [scottish-government-design-system/design-system#139]
## Description of the issue

This may or may not be a bug but your breakpoints for small is up to and including 767 pixels. (https://designsystem.gov.scot/styles/column-grid)

Your breakpoint for tables turning to boxes is up to 766px, 1 pixel less

Should these not be the same?

![image](https://github.com/user-attachments/assets/f395861f-faf1-4fc9-84eb-afa6f58b43ab)

## Steps to reproduce the issue

Check it on your own table boxes example

## Expected behaviour

I would expect both to be 767px

**Comment by jsutcliffe** [comment]
Hello, the only browser I can recreate this on is Edge on a Scottish Government SCOTS machine. It behaves in all other browsers I've tried, including Edge on a non-SCOTS PC. Can you provide any additional info such as browser version, OS version, etc?

**Comment by 72gm** [comment]
works on any browser, chrome, edge

use this link and set the pixels to 767... we see full table when this should start at 768... boxes should be 0 to < 768?
https://designsystem.gov.scot/components/table/boxes

![image](https://github.com/user-attachments/assets/9ed39e78-a1bb-4b83-9bed-9d8ca09b62d4)

Breaks at boxes at 766 rather than 767
![image](https://github.com/user-attachments/assets/cb752ef7-f337-4539-91e4-5863ae95ec1e)

**Comment by jsutcliffe** [comment]
This is what I see in all browsers I have checked with the exception of Edge on a SG SCOTS computer. I see this in Chrome, Firefox, Safari and Edge on MacOS. I see this in Chrome, Firefox and Edge on a non-SCOTS Windows PC.

![box-tables](https://github.com/user-attachments/assets/8e5f23c7-2da0-45ea-9ef2-9b17b59982c0)

Your issue is very perplexing.

**Comment by 72gm** [comment]
very odd! I'm seeing this behaviour on both work and personal laptops

I'm not going to worry too much about 1px, just seemed very strange... It was a tester that raised it... I'll tell them its not a bug ;)

**Comment by jsutcliffe** [comment]
OK, I'll close this for now but it feels like a loose end and I don't like those. Hopefully we'll find a reliable way of recreating it.
