### ISSUE TITLE
SVG blocked outside of gov.scot

### ISSUE THREAD

**Issue by craigo1409** [scottish-government-design-system/design-system#2]
Hi,

I'm trying to use this within our NHS application but getting blocked error when accessing icons.stack.svg.
This breaks a number of components (DatePicker calendar, Radio Buttons, Checkmarks).

I have tested this on localhost and pushed in our test environment and behaviour is consistent.

![image](https://user-images.githubusercontent.com/39034790/109486810-4446f880-7a7b-11eb-830d-4354fa22445d.png)

**Comment by DavidChristiansen** [comment]
Solve this by overriding the `$iconsfile` variable with the path to your `icon.stack.svg` file, before you import the scss files into yours.

for example
```
    $iconsfile: '/img/icons.stack.svg';
    @import '/path/to/base/node_modules/@scottish-government/pattern-library/src/base/_all-base';
```

HTH

**Comment by jsutcliffe** [comment]
Thank you @DavidChristiansen. That is the intended way to specify your icons path.
