### ISSUE TITLE
[Summary List] Bottom border of summary list items does not show in Safari

### ISSUE THREAD

**Issue by lewisdorigo** [scottish-government-design-system/design-system#25]
The bottom border on each item is not visible in Safari from the medium breakpoint up.

Tested on:
- Safari 16.2 on macOS
- Safari 15.5 on iPadOS

From testing, it appears that the `::after` pseudo element is being incorrectly positioned towards the bottom of the viewport while `.ds_summary-list__item` has `display: table-row;`.

This could be resolved by simply using `border-bottom`, rather than emulating a border using a pseudo-element.

See below screenshots:
![Screenshot 2023-01-13 at 7 50 31 am](https://user-images.githubusercontent.com/4225197/212266542-3e8f21d7-b6cc-4a51-919a-7fd84c19cb18.png)

![Simulator Screen Shot - iPad Air (5th generation) - 2023-01-13 at 07 49 56](https://user-images.githubusercontent.com/4225197/212266407-0e986d16-3bd5-4168-925b-61e972a6af46.png)

![Screenshot 2023-01-13 at 7 52 57 am](https://user-images.githubusercontent.com/4225197/212267040-7441a773-628e-476a-8042-fd53ae82ca52.png)

**Comment by jsutcliffe** [comment]
This has been resolved with border-bottom.
